// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingWebsite.Models;

namespace TrainingWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200403132915_SeedDataAdded")]
    partial class SeedDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrainingWebsite.Models.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProductsOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("categoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ImageThumbnailUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.notonthehighstreet.com%2Ffs%2F73%2F50%2Fe3c2-0e7b-4454-aaaa-a17f90d515c0%2Foriginal_baby-s-thoughts-personalised-baby-vest.jpg&imgrefurl=https%3A%2F%2Fwww.notonthehighstreet.com%2Flovetreedesign%2Fproduct%2Fbaby-s-thoughts-personalised-baby-vest&tbnid=ENo7oXMThUbcLM&vet=12ahUKEwjO14LTrMzoAhVJ44UKHdXKCSMQMygQegUIARCXBA..i&docid=VlZsgm5gDBhZrM&w=900&h=900&itg=1&q=personalised%20baby%20vest&ved=2ahUKEwjO14LTrMzoAhVJ44UKHdXKCSMQMygQegUIARCXBA",
                            ImageUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.notonthehighstreet.com%2Ffs%2F73%2F50%2Fe3c2-0e7b-4454-aaaa-a17f90d515c0%2Foriginal_baby-s-thoughts-personalised-baby-vest.jpg&imgrefurl=https%3A%2F%2Fwww.notonthehighstreet.com%2Flovetreedesign%2Fproduct%2Fbaby-s-thoughts-personalised-baby-vest&tbnid=ENo7oXMThUbcLM&vet=12ahUKEwjO14LTrMzoAhVJ44UKHdXKCSMQMygQegUIARCXBA..i&docid=VlZsgm5gDBhZrM&w=900&h=900&itg=1&q=personalised%20baby%20vest&ved=2ahUKEwjO14LTrMzoAhVJ44UKHdXKCSMQMygQegUIARCXBA",
                            InStock = true,
                            IsProductsOfTheWeek = true,
                            LongDescription = " Choose your color, choose your style and your message and we will create it for your perfect gift",
                            Price = 0m,
                            ProductName = "Personalised Baby Vest",
                            ShortDescription = "Create your own personalised baby vest",
                            categoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            ImageThumbnailUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.notonthehighstreet.com%2Ffs%2F71%2Fb6%2F8b74-40e3-4423-a3d3-6f4c3b310c98%2Foriginal_black-make-up-case-with-gold-name.jpg&imgrefurl=https%3A%2F%2Fwww.notonthehighstreet.com%2Ftillyanna%2Fproduct%2Fblack-make-up-case-with-gold-name&tbnid=CWHGdp54qIn45M&vet=12ahUKEwjWqcKirczoAhUL8hoKHeLCB-gQMygEegUIARDnAw..i&docid=dsLIPlLBu5NWrM&w=900&h=900&q=personalised%20makeupbag&ved=2ahUKEwjWqcKirczoAhUL8hoKHeLCB-gQMygEegUIARDnAw",
                            ImageUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.notonthehighstreet.com%2Ffs%2F71%2Fb6%2F8b74-40e3-4423-a3d3-6f4c3b310c98%2Foriginal_black-make-up-case-with-gold-name.jpg&imgrefurl=https%3A%2F%2Fwww.notonthehighstreet.com%2Ftillyanna%2Fproduct%2Fblack-make-up-case-with-gold-name&tbnid=CWHGdp54qIn45M&vet=12ahUKEwjWqcKirczoAhUL8hoKHeLCB-gQMygEegUIARDnAw..i&docid=dsLIPlLBu5NWrM&w=900&h=900&q=personalised%20makeupbag&ved=2ahUKEwjWqcKirczoAhUL8hoKHeLCB-gQMygEegUIARDnAw",
                            InStock = true,
                            IsProductsOfTheWeek = true,
                            LongDescription = " Choose your color, choose your style and your message and we will create it for your perfect gift",
                            Price = 0m,
                            ProductName = "Personalised Make-up Bag",
                            ShortDescription = "Create your own personalised Make-up bag",
                            categoryId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            ImageThumbnailUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.etsystatic.com%2F9610540%2Fr%2Fil%2Fad6b60%2F1491677050%2Fil_570xN.1491677050_929h.jpg&imgrefurl=https%3A%2F%2Fwww.etsy.com%2Fno-en%2Flisting%2F611151275%2Fpersonalised-water-bottle-personalised&tbnid=sWX5ppmIcTmhcM&vet=12ahUKEwjq1uLVrczoAhUj-YUKHbT4Co8QMygHegUIARCUBA..i&docid=kplrE0Di_whHYM&w=570&h=428&itg=1&q=personalised%20water%20bottle&ved=2ahUKEwjq1uLVrczoAhUj-YUKHbT4Co8QMygHegUIARCUBA",
                            ImageUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.etsystatic.com%2F9610540%2Fr%2Fil%2Fad6b60%2F1491677050%2Fil_570xN.1491677050_929h.jpg&imgrefurl=https%3A%2F%2Fwww.etsy.com%2Fno-en%2Flisting%2F611151275%2Fpersonalised-water-bottle-personalised&tbnid=sWX5ppmIcTmhcM&vet=12ahUKEwjq1uLVrczoAhUj-YUKHbT4Co8QMygHegUIARCUBA..i&docid=kplrE0Di_whHYM&w=570&h=428&itg=1&q=personalised%20water%20bottle&ved=2ahUKEwjq1uLVrczoAhUj-YUKHbT4Co8QMygHegUIARCUBA",
                            InStock = true,
                            IsProductsOfTheWeek = true,
                            LongDescription = " Choose your color, choose your style and your message and we will create it for your perfect gift",
                            Price = 0m,
                            ProductName = "Personalised Water Bottle",
                            ShortDescription = "Create your own personalised Water Bottle",
                            categoryId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            ImageThumbnailUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.etsy.com%2Fuk%2Fmarket%2Fpersonalised_storage&psig=AOvVaw1_wolBKZ7U14S2brSuegNE&ust=1586006847088000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIjX0YmuzOgCFQAAAAAdAAAAABAI",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.etsy.com%2Fuk%2Fmarket%2Fpersonalised_storage&psig=AOvVaw1_wolBKZ7U14S2brSuegNE&ust=1586006847088000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIjX0YmuzOgCFQAAAAAdAAAAABAI",
                            InStock = true,
                            IsProductsOfTheWeek = true,
                            LongDescription = " Choose your color, choose your style and your message and we will create it for your perfect gift",
                            Price = 0m,
                            ProductName = "Personalised Container",
                            ShortDescription = "Create your own personalised Containers",
                            categoryId = 2
                        });
                });

            modelBuilder.Entity("TrainingWebsite.Models.ViewModels.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Personalised Clothing",
                            Description = "Personalise Any Item of clothing for any occasion"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Personalised Soft Toys",
                            Description = "Personalise Any Soft Toy for any occasion"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Personalised Storage",
                            Description = "Personalise Any Item of storage for any item"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Personalised Ornaments",
                            Description = "Personalise Any Ornament for any occasion"
                        });
                });

            modelBuilder.Entity("TrainingWebsite.Models.Products", b =>
                {
                    b.HasOne("TrainingWebsite.Models.ViewModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
